files:
  - source: /src/main/resources/assets/modular_machinery_reborn_mekanism/lang/*.json
    translation: /src/main/resources/assets/modular_machinery_reborn_mekanism/lang/%locale_with_underscore%.json
